[package]
name = "itad-waitlist-api"
version = "1.1.1"
edition = "2024"

[dependencies]
actix-web = "4"
env_logger = "0.11"
dotenv = "0.15"
rss = "2.0"
scraper = "0.24.0"
reqwest = { version = "0.11", features = ["blocking"] }
serde = "1.0.228"
